name: Feature Request
description: Suggest a new feature or improvement for the registry
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: What problem does this solve?
      placeholder: Describe the problem or use case
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see?
      placeholder: Describe the feature or change
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've considered
      placeholder: Optional
    validations:
      required: false
